apiVersion: batch/v1
kind: CronJob
metadata:
  name: ai-infra-reporter
  namespace: monitoring
spec:
  schedule: "0 0 * * *" # 매일 UTC 0시 (한국시간 오전 9시)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reporter
            image: 604048704500.dkr.ecr.ap-northeast-2.amazonaws.com/my-k8s-api:latest
            command: ["python", "reporter.py"]
            env:
            - name: PROMETHEUS_URL
              value: "http://prometheus-kube-prometheus-prometheus.monitoring:9090"
            - name: PYTHONIOENCODING
              value: "utf-8"
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-secret
                  key: webhook-url
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secret
                  key: api-key
          restartPolicy: OnFailure
